version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: web_library
    ports:
      - 5432:5432

  adminer:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80