drop table if exists Person cascade;

create table if not exists Person
(
    id            int primary key generated by default as identity,
    full_name     varchar(100) not null unique,
    year_of_birth int check (year_of_birth > 0)
);

insert into person (full_name, year_of_birth)
values ('Иванов Иван Иванович', 1970),
       ('Петров Петр Петрович', 1960),
       ('Алексеев Алексей Алексеевич', 1989);

drop table if exists Book cascade;

create table if not exists Book
(
    id        int primary key generated by default as identity,
    name      varchar not null,
    author    varchar not null,
    year      int check (year > 0),
    person_id int     references Person (id) on delete set null
);

insert into Book (name, author, year)
values ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018),
       ('Бытие и время', 'Мартин Хайдеггер', 1927),
       ('Над пропастью во ржи', 'Джером Сэлиджер', 1951),
       ('Философия Java', 'Брюс Эккель', 2018),
       ('Психопатология обыденной жизни', 'Фрейд Зигмунд', 1904),
       ('День опричника', 'Владимир Сорокин', 2006),
       ('Игра в бисер', 'Герман Гессе', 1943);
