drop table if exists Person cascade;

create table if not exists Person
(
    id            int primary key generated by default as identity,
    full_name     varchar(100) not null unique,
    year_of_birth int check (year_of_birth > 0)
);

drop table if exists Book cascade;

create table if not exists Book
(
    id        int primary key generated by default as identity,
    name      varchar not null,
    author    varchar not null,
    year      int check (year > 0),
    person_id int     references Person (id) on delete set null
);
