CREATE TABLE measurements (
    measurement_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raining        BOOLEAN NOT NULL,
    sensor_id      INT     REFERENCES sensors(sensor_id) ON DELETE SET NULL
);