DROP SCHEMA IF EXISTS rest_api CASCADE;
CREATE SCHEMA IF NOT EXISTS rest_api;

CREATE TABLE IF NOT EXISTS rest_api.Sensor (
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS rest_api.Measuring (
    id        INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value     DOUBLE PRECISION,
    raining   BOOLEAN,
    sensor_id INT REFERENCES rest_api.Sensor(id)
);

INSERT INTO rest_api.Sensor (name)
VALUES ('test1'),
    ('test2');

INSERT INTO rest_api.Measuring (value, raining, sensor_id)
VALUES (144.3, TRUE, 1),
    (142, FALSE, 2);

