drop schema if exists rest_api cascade;
create schema if not exists rest_api;

create table if not exists rest_api.Sensor
(
    id   int primary key generated by default as identity,
    name varchar(30)
);

create table if not exists rest_api.Measuring
(
    id        int primary key generated by default as identity,
    value     double precision,
    raining   boolean,
    sensor_id int references rest_api.Sensor (id)
);

insert into rest_api.Sensor (name)
values ('test1'),
       ('test2');

insert into rest_api.Measuring (value, raining, sensor_id)
values (144.3, true, 1),
       (142, false, 2);

