drop table if exists Person cascade;

create table if not exists Person (
  id int generated by default as identity primary key,
  full_name varchar not null unique,
  year int not null
);

insert into person (full_name, year) values
('Иванов Иван Иванович', 1970),
('Петров Петр Петрович', 1960),
('Алексеев Алексей Алексеевич', 1989);

drop table if exists Book cascade;

create table if not exists Book (
  id int generated by default as identity primary key,
  name varchar not null,
  author varchar not null,
  year int not null,
  person_id int references person(id) on delete set null
);

insert into Book (name, author, year) values
('Над пропастью во ржи', 'Джером Сэлиджер', 1951),
('День опричника', 'Владимир Сорокин', 2006),
('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018);
