CREATE TABLE IF NOT EXISTS People (
    person_id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(100) NOT NULL,
    year_of_birth INT          NOT NULL,
    password      VARCHAR      NOT NULL,
    role          VARCHAR      NOT NULL
);